format:
  html:
    toc: true
    toc-depth: 4
    theme: [cosmo, notebooks/custom.scss]
    number-sections: false
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  chapters: [index.qmd, ppi_docs.api_reference.qmd, ppi_docs.preparations.qmd, ppi_docs.analysis.qmd]
  title: PPI RMSSD Data Analysis Library
